const languages = [
    { code: 'ab', language: 'Abkhazian' },
    { code: 'aa', language: 'Afar' },
    { code: 'af', language: 'Afrikaans' },
    { code: 'ak', language: 'Akan' },
    { code: 'sq', language: 'Albanian' },
    { code: 'am', language: 'Amharic' },
    { code: 'ar', language: 'Arabic' },
    { code: 'an', language: 'Aragonese' },
    { code: 'hy', language: 'Armenian' },
    { code: 'as', language: 'Assamese' },
    { code: 'av', language: 'Avaric' },
    { code: 'ae', language: 'Avestan' },
    { code: 'ay', language: 'Aymara' },
    { code: 'az', language: 'Azerbaijani' },
    { code: 'bm', language: 'Bambara' },
    { code: 'ba', language: 'Bashkir' },
    { code: 'eu', language: 'Basque' },
    { code: 'be', language: 'Belarusian' },
    { code: 'bn', language: 'Bengali' },
    { code: 'bh', language: 'Bihari languages' },
    { code: 'bi', language: 'Bislama' },
    { code: 'bs', language: 'Bosnian' },
    { code: 'br', language: 'Breton' },
    { code: 'bg', language: 'Bulgarian' },
    { code: 'my', language: 'Burmese' },
    { code: 'ca', language: 'Catalan, Valencian' },
    { code: 'km', language: 'Central Khmer' },
    { code: 'ch', language: 'Chamorro' },
    { code: 'ce', language: 'Chechen' },
    { code: 'ny', language: 'Chichewa, Chewa, Nyanja' },
    { code: 'zh', language: 'Chinese' },
    {
        code: 'cu',
        language: 'Church Slavonic, Old Bulgarian, Old Church Slavonic',
    },
    { code: 'cv', language: 'Chuvash' },
    { code: 'kw', language: 'Cornish' },
    { code: 'co', language: 'Corsican' },
    { code: 'cr', language: 'Cree' },
    { code: 'hr', language: 'Croatian' },
    { code: 'cs', language: 'Czech' },
    { code: 'da', language: 'Danish' },
    { code: 'dv', language: 'Divehi, Dhivehi, Maldivian' },
    { code: 'nl', language: 'Dutch, Flemish' },
    { code: 'dz', language: 'Dzongkha' },
    { code: 'en', language: 'English' },
    { code: 'eo', language: 'Esperanto' },
    { code: 'et', language: 'Estonian' },
    { code: 'ee', language: 'Ewe' },
    { code: 'fo', language: 'Faroese' },
    { code: 'fj', language: 'Fijian' },
    { code: 'fi', language: 'Finnish' },
    { code: 'fr', language: 'French' },
    { code: 'ff', language: 'Fulah' },
    { code: 'gd', language: 'Gaelic, Scottish Gaelic' },
    { code: 'gl', language: 'Galician' },
    { code: 'lg', language: 'Ganda' },
    { code: 'ka', language: 'Georgian' },
    { code: 'de', language: 'German' },
    { code: 'ki', language: 'Gikuyu, Kikuyu' },
    { code: 'el', language: 'Greek (Modern)' },
    { code: 'kl', language: 'Greenlandic, Kalaallisut' },
    { code: 'gn', language: 'Guarani' },
    { code: 'gu', language: 'Gujarati' },
    { code: 'ht', language: 'Haitian, Haitian Creole' },
    { code: 'ha', language: 'Hausa' },
    { code: 'he', language: 'Hebrew' },
    { code: 'hz', language: 'Herero' },
    { code: 'hi', language: 'Hindi' },
    { code: 'ho', language: 'Hiri Motu' },
    { code: 'hu', language: 'Hungarian' },
    { code: 'is', language: 'Icelandic' },
    { code: 'io', language: 'Ido' },
    { code: 'ig', language: 'Igbo' },
    { code: 'id', language: 'Indonesian' },
    {
        code: 'ia',
        language: 'Interlingua (International Auxiliary Language Association)',
    },
    { code: 'ie', language: 'Interlingue' },
    { code: 'iu', language: 'Inuktitut' },
    { code: 'ik', language: 'Inupiaq' },
    { code: 'ga', language: 'Irish' },
    { code: 'it', language: 'Italian' },
    { code: 'ja', language: 'Japanese' },
    { code: 'jv', language: 'Javanese' },
    { code: 'kn', language: 'Kannada' },
    { code: 'kr', language: 'Kanuri' },
    { code: 'ks', language: 'Kashmiri' },
    { code: 'kk', language: 'Kazakh' },
    { code: 'rw', language: 'Kinyarwanda' },
    { code: 'kv', language: 'Komi' },
    { code: 'kg', language: 'Kongo' },
    { code: 'ko', language: 'Korean' },
    { code: 'kj', language: 'Kwanyama, Kuanyama' },
    { code: 'ku', language: 'Kurdish' },
    { code: 'ky', language: 'Kyrgyz' },
    { code: 'lo', language: 'Lao' },
    { code: 'la', language: 'Latin' },
    { code: 'lv', language: 'Latvian' },
    { code: 'lb', language: 'Letzeburgesch, Luxembourgish' },
    { code: 'li', language: 'Limburgish, Limburgan, Limburger' },
    { code: 'ln', language: 'Lingala' },
    { code: 'lt', language: 'Lithuanian' },
    { code: 'lu', language: 'Luba-Katanga' },
    { code: 'mk', language: 'Macedonian' },
    { code: 'mg', language: 'Malagasy' },
    { code: 'ms', language: 'Malay' },
    { code: 'ml', language: 'Malayalam' },
    { code: 'mt', language: 'Maltese' },
    { code: 'gv', language: 'Manx' },
    { code: 'mi', language: 'Maori' },
    { code: 'mr', language: 'Marathi' },
    { code: 'mh', language: 'Marshallese' },
    { code: 'ro', language: 'Moldovan, Moldavian, Romanian' },
    { code: 'mn', language: 'Mongolian' },
    { code: 'na', language: 'Nauru' },
    { code: 'nv', language: 'Navajo, Navaho' },
    { code: 'nd', language: 'Northern Ndebele' },
    { code: 'ng', language: 'Ndonga' },
    { code: 'ne', language: 'Nepali' },
    { code: 'se', language: 'Northern Sami' },
    { code: 'no', language: 'Norwegian' },
    { code: 'nb', language: 'Norwegian Bokmål' },
    { code: 'nn', language: 'Norwegian Nynorsk' },
    { code: 'ii', language: 'Nuosu, Sichuan Yi' },
    { code: 'oc', language: 'Occitan (post 1500)' },
    { code: 'oj', language: 'Ojibwa' },
    { code: 'or', language: 'Oriya' },
    { code: 'om', language: 'Oromo' },
    { code: 'os', language: 'Ossetian, Ossetic' },
    { code: 'pi', language: 'Pali' },
    { code: 'pa', language: 'Panjabi, Punjabi' },
    { code: 'ps', language: 'Pashto, Pushto' },
    { code: 'fa', language: 'Persian' },
    { code: 'pl', language: 'Polish' },
    { code: 'pt', language: 'Portuguese' },
    { code: 'qu', language: 'Quechua' },
    { code: 'rm', language: 'Romansh' },
    { code: 'rn', language: 'Rundi' },
    { code: 'ru', language: 'Russian' },
    { code: 'sm', language: 'Samoan' },
    { code: 'sg', language: 'Sango' },
    { code: 'sa', language: 'Sanskrit' },
    { code: 'sc', language: 'Sardinian' },
    { code: 'sr', language: 'Serbian' },
    { code: 'sn', language: 'Shona' },
    { code: 'sd', language: 'Sindhi' },
    { code: 'si', language: 'Sinhala, Sinhalese' },
    { code: 'sk', language: 'Slovak' },
    { code: 'sl', language: 'Slovenian' },
    { code: 'so', language: 'Somali' },
    { code: 'st', language: 'Sotho, Southern' },
    { code: 'nr', language: 'South Ndebele' },
    { code: 'es', language: 'Spanish, Castilian' },
    { code: 'su', language: 'Sundanese' },
    { code: 'sw', language: 'Swahili' },
    { code: 'ss', language: 'Swati' },
    { code: 'sv', language: 'Swedish' },
    { code: 'tl', language: 'Tagalog' },
    { code: 'ty', language: 'Tahitian' },
    { code: 'tg', language: 'Tajik' },
    { code: 'ta', language: 'Tamil' },
    { code: 'tt', language: 'Tatar' },
    { code: 'te', language: 'Telugu' },
    { code: 'th', language: 'Thai' },
    { code: 'bo', language: 'Tibetan' },
    { code: 'ti', language: 'Tigrinya' },
    { code: 'to', language: 'Tonga (Tonga Islands)' },
    { code: 'ts', language: 'Tsonga' },
    { code: 'tn', language: 'Tswana' },
    { code: 'tr', language: 'Turkish' },
    { code: 'tk', language: 'Turkmen' },
    { code: 'tw', language: 'Twi' },
    { code: 'ug', language: 'Uighur, Uyghur' },
    { code: 'uk', language: 'Ukrainian' },
    { code: 'ur', language: 'Urdu' },
    { code: 'uz', language: 'Uzbek' },
    { code: 've', language: 'Venda' },
    { code: 'vi', language: 'Vietnamese' },
    { code: 'vo', language: 'Volap_k' },
    { code: 'wa', language: 'Walloon' },
    { code: 'cy', language: 'Welsh' },
    { code: 'fy', language: 'Western Frisian' },
    { code: 'wo', language: 'Wolof' },
    { code: 'xh', language: 'Xhosa' },
    { code: 'yi', language: 'Yiddish' },
    { code: 'yo', language: 'Yoruba' },
    { code: 'za', language: 'Zhuang, Chuang' },
    { code: 'zu', language: 'Zulu' },
];

export default languages;
