# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./backend
    runs-on: self-hosted
    env: 
           NODE_ENV: production
           MONGO_URI: ongodb+srv://muneebmnb123:Qgx4eXmlpqMAzkhb@platformcluster0.jlfd6rp.mongodb.net/PlatformVideoSharing?retryWrites=true&w=majority 
           PORT: 5000
           JWT_SECRET: 2a$15$zFAQiLzUSolcDemH/Jz5huj1edIvOsaPxe86G19zJpIIP8gU3.JvS
           GOOGLE_API_KEY: AIzaSyDW-qMa5z8QvSdj4AUMyKcm64Gtlyp7RjI
           GOOGLE_CLIENT_ID: 374719203399-7pj5d7ngbj8vmcponcdhh3ingg8bc9qk.apps.googleusercontent.com
           GOOGLE_CLIENT_SECRET: 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
           FACEBOOK_APP_ID: 449652870455804
           FACEBOOK_APP_SECRET: 0cdef462688784a08103726d1522c2
           ROOT_URL: https://vplatform.ga
           CLOUDINARY_CLOUD_NAME: drjndmchy
           CLOUDINARY_API_KEY: 514344456187884
           CLOUDINARY_API_SECRET: H_KfTmcils1DAaZsjHJ2DBdD0VU
           CLOUDINARY_URL: cloudinary://514344456187884:H_KfTmcils1DAaZsjHJ2DBdD0VU@drjndmchy
           NODEMAILER_AUTH_USER: muneebmnbth17@outlook.com
           NODEMAILER_AUTH_PASSWORD: MS79Q3hXwGc5cuc
           NODEMAILER_FROM_EMAIL: Platform-Video sharing<platformvideosharing@outlook.com>
           NODEMAILER_SERVICE: hotmail
           FRONTEND_HOST_NAME: https://vplatform.cf


    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: pm2 restart app.js
      
